// RAW LAYER
// Source-aligned ingestion with minimal transformation.

SET ErrorMode=1;
SET DateFormat='YYYY-MM-DD';
SET TimestampFormat='YYYY-MM-DD hh:mm:ss';

$(Must_Include=../config/environment.qvs);

Customers_Raw:
LOAD
    CustomerID,
    CustomerName,
    Region,
    Country,
    Segment
FROM [$(vSourcePath)customers.csv]
(txt, codepage is 65001, embedded labels, delimiter is ',', msq);
STORE Customers_Raw INTO [$(vRawQvdPath)Customers.qvd] (qvd);
DROP TABLE Customers_Raw;

Products_Raw:
LOAD
    ProductID,
    ProductName,
    Category,
    Subcategory,
    UnitPrice
FROM [$(vSourcePath)products.csv]
(txt, codepage is 65001, embedded labels, delimiter is ',', msq);
STORE Products_Raw INTO [$(vRawQvdPath)Products.qvd] (qvd);
DROP TABLE Products_Raw;

Orders_Raw:
LOAD
    OrderID,
    OrderDate,
    CustomerID,
    ProductID,
    Quantity,
    Discount,
    SalesAmount,
    ModifiedDate
FROM [$(vSourcePath)orders.csv]
(txt, codepage is 65001, embedded labels, delimiter is ',', msq);
STORE Orders_Raw INTO [$(vRawQvdPath)Orders.qvd] (qvd);
DROP TABLE Orders_Raw;

TRACE RAW LAYER COMPLETE;
